Fix CMakeLists
Kvalme/RadeonProRender-Baikal pull request #10
Opened 2018-08-16 10:55 UTC by AlexanderVeselov

2018-08-16 11:06 UTC, Kvalme requested changes
Please, revert all cosmetic changes

2018-08-16 11:06 UTC, Kvalme commented on Baikal/CMakeLists.txt
> +)
Please, revert

2018-08-16 11:19 UTC, Kvalme requested changes

2018-08-16 11:19 UTC, Kvalme commented on Baikal/CMakeLists.txt
> -
not reverted

2018-08-17 07:04 UTC, Kvalme requested changes

2018-08-17 07:04 UTC, Kvalme commented on Baikal/CMakeLists.txt
> +        COMMAND IF NOT EXIST ${BAIKAL_KERNELS_DST} mklink /D ${BAIKAL_KERNELS_DST} ${BAIKAL_KERNELS_SRC}
cmake -E create_symlink don't work on windows?

2018-08-17 07:04 UTC, Kvalme commented on BaikalTest/CMakeLists.txt
> -FILE(TO_NATIVE_PATH ${Baikal_SOURCE_DIR}/BaikalTest/${BAIKALTEST_REFERENCEIMAGES_DIR} BAIKALTEST_REFERENCEIMAGES_SRC)
please, revert

2018-08-17 09:00 UTC, AlexanderVeselov commented on BaikalTest/CMakeLists.txt
> -FILE(TO_NATIVE_PATH ${Baikal_SOURCE_DIR}/BaikalTest/${BAIKALTEST_REFERENCEIMAGES_DIR} BAIKALTEST_REFERENCEIMAGES_SRC)
Ok

2018-08-17 09:00 UTC, AlexanderVeselov commented on Baikal/CMakeLists.txt
> +        COMMAND IF NOT EXIST ${BAIKAL_KERNELS_DST} mklink /D ${BAIKAL_KERNELS_DST} ${BAIKAL_KERNELS_SRC}
No, only Unix

2018-08-17 09:41 UTC, Kvalme commented
Ok. Create external review

2018-08-23 08:50 UTC, closed without merging