Rewrite rpr test
Kvalme/RadeonProRender-Baikal pull request #4
Opened 2018-05-22 12:04 UTC by AlexanderVeselov

2018-05-25 11:46 UTC, Kvalme requested changes

2018-05-25 11:46 UTC, Kvalme commented on Rpr/WrapObject/ContextObject.cpp
> +    { RPR_CONTEXT_RANDOM_SEED,{ "randseed", "Random seed", RPR_PARAMETER_TYPE_UINT } },
It's better to add value to the end not in the middle

2018-05-25 11:46 UTC, Kvalme commented on RprTest/aov.h
> +        ASSERT_EQ(rprContextCreateFrameBuffer(m_context, fmt, &desc, &m_framebuffer), RPR_SUCCESS);
Clean framebuffer before use or we clean it in rprContextCreateFrameBuffer?

2018-05-25 11:46 UTC, Kvalme commented on RprTest/arithmetic.h
> +// This doesn't work
Please, check and provide more info

2018-05-25 11:54 UTC, AlexanderVeselov commented on RprTest/aov.h
> +        ASSERT_EQ(rprContextCreateFrameBuffer(m_context, fmt, &desc, &m_framebuffer), RPR_SUCCESS);
We clean it in BasicTest::Render() before taking render samples

2018-06-01 08:42 UTC, Kvalme commented on RprTest/basic.h
> +    static std::uint32_t constexpr kRenderIterations = 256;
Please, made this change only for Bump and Normal map tests. Not for all tests

2018-06-04 07:13 UTC, closed without merging